### ISSUE TITLE
[Class01 HW#1] Github Issue 실습 - <내이름>

### ISSUE THREAD

**Issue by mokiya** [kccistc/intel-04#1]
다음의 내용으로 Issue ticket을 생성하고 milestone 등을 설정합니다.

- [ ] Issue ticket을 생성하고 다음 내용을 작성
  * Name: <내 이름>
  * Github ID: <내 Github ID>
  * My repo: <생성한 repo의 URL>
- [ ] Assignee를 본인에게 할당
- [ ] Milestone을 "[Class01 HW#1] Github Issue 실습"으로 설정

**Comment by jhj4748201** [comment]
name: jeong hee jung

GitHub ID : jhj4748201@gmail.com

My repo : https://github.com/jhj4748201/My-project.git
