### ISSUE TITLE
[Class01 HW#1] Github Issue 실습 - 정용재

### ISSUE THREAD

**Issue by eolgaemi** [kccistc/intel-04#11]
Name: 정용재
Github ID: yjwlm10@daum.net
My repo: https://github.com/eolgaemi/pepper_dryer.git

**Comment by kccistc** [comment]
yjwlm10@daum.net 메일로 invitation이 전달되었을텐데, 확인부탁해요~ :)

**Comment by eolgaemi** [comment]
확인했습니다!
