### ISSUE TITLE
[Class01 HW#1] Github Issue 실습 - <이윤혁>

### ISSUE THREAD

**Issue by YuNyuk** [kccistc/intel-04#17]
Name: <이윤혁>
Github ID: YuNyuk
My repo: <https://github.com/YuNyuk/intel_test.git>

**Comment by kccistc** [comment]
Github ID가 YuNyuk 맞나요? :)

**Comment by YuNyuk** [comment]
> Github ID가 YuNyuk 맞나요? :)

앗 네네 맞습니다! 에딧창에는 뜨는데 안뜨네요 ㅠ
